Addition and small fix
miljanuscumlic/cli-commands pull request #3
Opened 2020-04-10 12:38 UTC by eevan78

Hi Miljan!
I have found some errors in links on README.md and I have contributed two more commands to git!

Great project!

2020-04-10 17:27 UTC, miljanuscumlic requested changes
Hi Ivan,
Thanks for your contribution. This is looking good, but there is one small issue that should be addressed before I merge it. I left a comment.

2020-04-10 17:27 UTC, miljanuscumlic commented on README.md
> +This project is licensed under the Unlicense - see the [UNLICENSE](https://github.com/miljanuscumlic/terminal-commands/blob/develop/UNLICENSE) file for details.
We will merge develop branch to a master, and then these links will not be correct again. Please change `develop` with `master` in those links.
We will keep in mind their temporary non-correctness until the branch gets merged into the master.

2020-04-11 06:47 UTC, eevan78 commented on README.md
> +This project is licensed under the Unlicense - see the [UNLICENSE](https://github.com/miljanuscumlic/terminal-commands/blob/develop/UNLICENSE) file for details.
That's a valid point. I missed it :) I will change branch to `master`.

2020-04-11 10:22 UTC, miljanuscumlic approved these changes
Great!

2020-04-11 10:24 UTC, merged